a=int(input("enter length1"))
b=int(input("enter width1"))
c=int(input("enter length2"))
d=int(input("enter width2"))
e=int(input("enter length3"))
f=int(input("enter width3"))
g=int(input("enter length4"))
h=int(input("enter width4"))
i=(a*b)
print(i)
j=(c*d)
print(j)
k=(e*f)
print(k)
l=(g*h)
print(l)
